In [2]:
import pandas as pd

/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [3]:
df = pd.read_csv('causes_of_death.tsv', delimiter='\t')
print(len(df))
df.head()

4115

,Notes,State,State Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Race,Race Code,Deaths,Population,Crude Rate
0,NaN,Alabama,1,< 1 year,1,Female,F,American Indian or Alaska Native,1002-5,14,3579,Unreliable
1,NaN,Alabama,1,< 1 year,1,Female,F,Asian or Pacific Islander,A-PI,24,7443,322.5
2,NaN,Alabama,1,< 1 year,1,Female,F,Black or African American,2054-5,2093,169339,1236.0
3,NaN,Alabama,1,< 1 year,1,Female,F,White,2106-3,2144,347921,616.2
4,NaN,Alabama,1,< 1 year,1,Male,M,Asian or Pacific Islander,A-PI,33,7366,448.0

# Practice Explorations

### Groupby State and Sum the numeric features.

In [48]:
# Groupby State
df[]

['3579',
 '7443',
 '169339',
 '347921',
 '7366',
 '173241',
 '364029',
 '30421',
 '670420',
 '1389699',
 '686063',
 '1457208',
 '1777031',
 '3608616',
 '72892',
 '1827893',
 '3809162',
 '77467',
 '1960325',
 '3811460',
 '49356',
 '86058',
 '1875654',
 '3988037',
 '40537',
 '97652',
 '1672441',
 '3710682',
 '43754',
 '96274',
 '1415384',
 '3807744',
 '43150',
 '90658',
 '1641941',
 '4077615',
 '42889',
 '82887',
 '1350006',
 '4119658',
 '43090',
 '71050',
 '1609494',
 '4334752',
 '41186',
 '57422',
 '1344952',
 '4284775',
 '30130',
 '48552',
 '1170060',
 '3824353',
 '30568',
 '34239',
 '960664',
 '3600218',
 '14251',
 '24770',
 '707809',
 '2828467',
 '14498',
 '16824',
 '514784',
 '2441673',
 '5577',
 '10042',
 '431705',
 '1834047',
 '4588',
 '5542',
 '235423',
 '1263438',
 '2087',
 '2173',
 '187517',
 '740184',
 '1129',
 '1269',
 '68421',
 '320674',
 'Not Applicable',
 '21687',
 '6031',
 '6134',
 '57813',
 '22888',
 '6493',
 '6865',
 '61322',
 '80050',
 '226065',
 '87405',
 '239284',
 '204061',
 '583142',
 '215827',
 '68517',
 '56130',
 '617059',
 '184265',
 '64629',
 '47206',
 '570394',
 '197269',
 '69911',
 '61212',
 '690094',
 '140538',
 '64892',
 '39463',
 '606254',
 '143936',
 '60493',
 '51141',
 '679294',
 '129831',
 '66575',
 '31937',
 '634167',
 '130988',
 '56032',
 '40569',
 '688995',
 '123356',
 '62701',
 '26554',
 '682855',
 '121823',
 '53269',
 '32854',
 '770502',
 '82861',
 '42568',
 '16003',
 '480410',
 '79952',
 '34411',
 '18833',
 '564787',
 '44837',
 '21437',
 '7335',
 '217054',
 '40498',
 '15076',
 '6917',
 '245602',
 '21738',
 '10315',
 '3502',
 '102924',
 '16501',
 '5576',
 '2669',
 '91310',
 '6812',
 '2641',
 '1224',
 '39350',
 '3562',
 '1360',
 '578',
 '21510',
 '62146',
 '25807',
 '48272',
 '633359',
 '62862',
 '27000',
 '51518',
 '660547',
 '235616',
 '105057',
 '189744',
 '2516461',
 '241195',
 '106433',
 '200314',
 '2628369',
 '580768',
 '243143',
 '445015',
 '6265346',
 '590354',
 '244496',
 '472420',
 '6561364',
 '562362',
 '251663',
 '414126',
 '6221135',
 '583146',
 '273705',
 '476396',
 '6692127',
 '442411',
 '338129',
 '367503',
 '6121081',
 '455881',
 '325939',
 '422483',
 '6528536',
 '397492',
 '316236',
 '328012',
 '6185574',
 '382657',
 '280697',
 '371850',
 '6349037',
 '344278',
 '242021',
 '272880',
 '6203576',
 '310761',
 '194666',
 '299246',
 '6041932',
 '228437',
 '172278',
 '181168',
 '5529755',
 '195163',
 '119752',
 '184838',
 '5047713',
 '130351',
 '99070',
 '102824',
 '4193850',
 '103961',
 '68251',
 '93100',
 '3801610',
 '62965',
 '43139',
 '49683',
 '2598498',
 '44624',
 '29213',
 '37557',
 '2151689',
 '22002',
 '12211',
 '18304',
 '1042324',
 '12318',
 '6877',
 '8790',
 '603932',
 'Not Applicable',
 'Not Applicable',
 'Not Applicable',
 'Not Applicable',
 '6218',
 '69140',
 '254940',
 '3860',
 '6638',
 '71191',
 '269654',
 '279764',
 '1018198',
 '25663',
 '287192',
 '1072145',
 '55862',
 '709470',
 '2603285',
 '56101',
 '725554',
 '2748762',
 '60235',
 '712536',
 '2688811',
 '40794',
 '64231',
 '709077',
 '2825813',
 '33692',
 '76260',
 '601761',
 '2597217',
 '34836',
 '73263',
 '530277',
 '2692101',
 '33417',
 '60913',
 '568551',
 '2749646',
 '32864',
 '54787',
 '487014',
 '2794896',
 '34555',
 '45805',
 '543437',
 '2878953',
 '32024',
 '37082',
 '473285',
 '2844754',
 '22820',
 '31002',
 '383596',
 '2588452',
 '22269',
 '22781',
 '330113',
 '2432112',
 '10954',
 '15043',
 '222118',
 '1949996',
 '10912',
 '10531',
 '167235',
 '1720703',
 '4466',
 '6099',
 '140078',
 '1262484',
 '4085',
 '3759',
 '78475',
 '918029',
 '1766',
 '1770',
 '67640',
 '547333',
 '1001',
 '818',
 '27258',
 '256109',
 '86884',
 '551654',
 '351914',
 '3488306',
 '90005',
 '585431',
 '367758',
 '3641682',
 '354623',
 '2235086',
 '1414629',
 '13713121',
 '365581',
 '2356608',
 '1472709',
 '14341786',
 '1004475',
 '5739701',
 '3853451',
 '34827429',
 '1030759',
 '6045728',
 '4006544',
 '36468574',
 '1007240',
 '6478270',
 '3820821',
 '34971287',
 '1085023',
 '6697557',
 '4049552',
 '38013386',
 '884989',
 '7897116',
 '3470786',
 '34894239',
 '960423',
 '7337759',
 '3485245',
 '37757802',
 '831873',
 '7882914',
 '3475121',
 '35338781',
 '852375',
 '6956009',
 '3407498',
 '37049536',
 '722185',
 '7091659',
 '3248951',
 '33946383',
 '712017',
 '6125511',
 '3113599',
 '34318006',
 '459676',
 '5225116',
 '2283069',
 '26158742',
 '433330',
 '4354736',
 '2043393',
 '25020860',
 '228944',
 '3252605',
 '1360928',
 '17026312',
 '200423',
 '2574023',
 '1094624',
 '14864965',
 '110587',
 '1881299',
 '764139',
 '11617960',
 '81405',
 '1348769',
 '504377',
 '8543274',
 '40061',
 '694013',
 '313298',
 '5521467',
 '22096',
 '416582',
 '136838',
 '2875802',
 'Not Applicable',
 'Not Applicable',
 'Not Applicable',
 'Not Applicable',
 'Not Applicable',
 'Not Applicable',
 '12487',
 '20956',
 '36382',
 '509758',
 '12834',
 '21150',
 '39203',
 '537194',
 '89239',
 '148881',
 '2019552',
 '49763',
 '85616',
 '157032',
 '2131463',
 '123476',
 '215951',
 '362965',
 '5102146',
 '124593',
 '203587',
 '379863',
 '5377040',
 '128157',
 '216061',
 '328047',
 '5188582',
 '135584',
 '215740',
 '372184',
 '5666761',
 '112941',
 '278713',
 '299139',
 '5533788',
 '123901',
 '256612',
 '352741',
 '5980727',
 '106977',
 '255621',
 '276056',
 '5692814',
 '111391',
 '217017',
 '330642',
 '5918190',
 '91775',
 '197163',
 '238075',
 '5769346',
 '92448',
 '157073',
 '275160',
 '5754380',
 '57677',
 '126905',
 '154951',
 '4466403',
 '56838',
 '94620',
 '163740',
 '4334825',
 '25948',
 '71563',
 '87042',
 '2667255',
 '24217',
 '49874',
 '77926',
 '2425150',
 '10816',
 '37162',
 '45837',
 '1623159',
 '8059',
 '23137',
 '32450',
 '1207233',
 '3638',
 '11482',
 '16134',
 '751767',
 '2021',
 '6118',
 '6673',
 '365067',
 'Not Applicable',
 '18534',
 '54220',
 '271747',
 '19098',
 '57037',
 '285911',
 '78222',
 '218325',
 '1152216',
 '76563',
 '229217',
 '1209838',
 '178678',
 '601126',
 '3294008',
 '174173',
 '626265',
 '3466570',
 '172530',
 '601870',
 '3234023',
 '29378',
 '173692',
 '626624',
 '3437981',
 '252900',
 '549042',
 '3041816',
 '239721',
 '500333',
 '3078038',
 '23991',
 '225359',
 '561783',
 '3904418',
 '24571',
 '214584',
 '481076',
 '3789771',
 '21247',
 '157647',
 '489847',
 '4284249',
 '20880',
 '148996',
 '418009',
 '4124481',
 '12512',
 '98304',
 '330105',
 '3382322',
 '12055',
 '88207',
 '267121',
 '3181232',
 '6196',
 '50357',
 '195900',
 '2226052',
 '5467',
 '44984',
 '139579',
 '1905871',
 '3404',
 '21030',
 '102394',
 '1694179',
 '2126',
 '17171',
 '60599',
 '1162726',
 '1300',
 '5916',
 '39172',
 '932967',
 '737',
 '3556',
 '15046',
 '421174',
 'Not Applicable',
 'Not Applicable',
 '4259',
 '27333',
 '64806',
 '4267',
 '27939',
 '67851',
 '107606',
 '257732',
 '109616',
 '270949',
 '284342',
 '664547',
 '292951',
 '696840',
 '289374',
 '743395',
 '288721',
 '758243',
 '248394',
 '714781',
 '51311',
 '219600',
 '722612',
 '44257',
 '266755',
 '784724',
 '7236',
 '42653',
 '226094',
 '776528',
 '5744',
 '34102',
 '250939',
 '854369',
 '29413',
 '208104',
 '822548',
 '4129',
 '23878',
 '172698',
 '762126',
 '4237',
 '19094',
 '139279',
 '695198',
 '2509',
 '14189',
 '99755',
 '565914',
 '2347',
 '11610',
 '77632',
 '498450',
 '1397',
 '5667',
 '51946',
 '358185',
 '1051',
 '4465',
 '32940',
 '269966',
 '516',
 '1488',
 '19702',
 '153985',
 '249',
 '916',
 '8354',
 '73686',
 '39752',
 '26508',
 '40167',
 '28279',
 '152621',
 '78730',
 '157749',
 '82328',
 '384665',
 '120406',
 '387946',
 '123585',
 '466927',
 '397486',
 '33180',
 '414197',
 '338099',
 '74636',
 '448256',
 '610212',
 '55003',
 '366754',
 '598018',
 '37330',
 '426452',
 '303848',
 '31862',
 '368593',
 '375577',
 '22016',
 '455419',
 '217310',
 '16897',
 '387364',
 '256527',
 '16653',
 '374321',
 '196569',
 '10851',
 '294629',
 '195176',
 '9323',
 '253006',
 '114070',
 '1393',
 '6159',
 '174620',
 '109387',
 '1027',
 '4574',
 '182294',
 '69203',
 '2820',
 '96265',
 '55278',
 '438',
 '2018',
 '81289',
 '41751',
 '1015',
 '29608',
 '21411',
 'Not Applicable',
 'Not Applicable',
 'Not Applicable',
 '13558',
 '56480',
 '450751',
 '1342342',
 '14482',
 '58477',
 '465482',
 '1406613',
 '228053',
 '1751569',
 '5354670',
 '50060',
 '229473',
 '1816542',
 '5623105',
 '572951',
 '4475306',
 '14100233',
 '118809',
 '571620',
 '4620636',
 '14854466',
 '120761',
 '623181',
 '4663177',
 '14959069',
 '143823',
 '632664',
 '4702697',
 '15986985',
 '113786',
 '797514',
 '4108044',
 '15350633',
 '140262',
 '703389',
 '3799348',
 '16050246',
 '119393',
 '804470',
 '3962096',
 '17620881',
 '131565',
 '674200',
 '3568857',
 '17861524',
 '116010',
 '689523',
 '3598841',
 '18892377',
 '119140',
 '543093',
 '3211002',
 '18346677',
 '79602',
 '496184',
 '2509296',
 '17340671',
 '80514',
 '375320',
 '2132211',
 '15657959',
 '40650',
 '285612',
 '1516410',
 '14563516',
 '39946',
 '220126',
 '1189068',
 '12817439',
 '18269',
 '120208',
 '819424',
 '10221501',
 '14859',
 '88571',
 '521246',
 '8132074',
 '6496',
 '35194',
 '315238',
 '4420955',
 '3700',
 '20952',
 '134440',
 '2558651',
 'Not Applicable',
 'Not Applicable',
 'Not Applicable',
 'Not Applicable',
 '7131',
 '41763',
 '407816',
 '711638',
 '7835',
 '44278',
 '419447',
 '748400',
 '171869',
 '1627852',
 '2810118',
 '27988',
 '177632',
 '1672839',
 '2950257',
 '399670',
 '4296293',
 '6968892',
 '408525',
 '4391923',
 '7354405',
 '402803',
 '4348591',
 '6925303',
 '75551',
 '432138',
 '4271730',
 '7569572',
 '62201',
 '550636',
 '4146964',
 '7302480',
 '76959',
 '504655',
 '3590316',
 '7759360',
 '61028',
 '523655',
 '4203047',
 '7872387',
 '66368',
 '483784',
 '3540693',
 '8150562',
 '49064',
 '386346',
 '3673809',
 '7788275',
 '50241',
 '351608',
 '3096996',
 '7779945',
 '29168',
 '245641',
 '2447860',
 '6320369',
 '30070',
 '211335',
 '1954810',
 '6010362',
 '12526',
 '125797',
 '1334798',
 '4209080',
 '13237',
 '105639',
 '949623',
 '3691831',
 '5390',
 '49095',
 '695125',
 '2572059',
 '3882',
 '37644',
 '370520',
 '1768340',
 '1804',
 '12312',
 '290899',
 '1079073',
 '808',
 '7287',
 '96821',
 '457882',
 'Not Applicable',
 'Not Applicable',
 '100371',
 '6895',
 '47674',
 '106549',
 '7462',
 '49042',
 '388242',
 '171573',
 '412779',
 '28028',
 '181560',
 '1022136',
 '367821',
 '1081608',
 '57360',
 '388764',
 '1009699',
 '52458',
 '419242',
 '1056469',
 '81518',
 '580653',
 '1028843',
 '54170',
 '501034',
 '10790',
 '1000019',
 '85934',
 '636028',
 '1116967',
 '34741',
 '447113',
 '8630',
 '1036374',
 '59121',
 '543380',
 '7234',
 '1136814',
 '19667',
 '492230',
 '7506',
 '1056827',
 '35877',
 '556779',
 '4975',
 '941409',
 '11443',
 '440555',
 '5263',
 '845403',
 '18994',
 '491918',
 '2038',
 '688548',
 '5524',
 '256980',
 '2349',
 '554414',
 '8346',
 '280184',
 '890',
 '502384',
 '2915',
 '146542',
 '798',
 '352000',
 '3399',
 '131677',
 '232',
 '238117',
 '978',
 '66157',
 '183',
 '141725',
 '1000',
 '41469',
 '5269',
 '3295',
 '3240',
 '185792',
 '5265',
 '3262',
 '3251',
 '193914',
 '736861',
 '773401',
 '1881123',
 '1988638',
 '40906',
 '35112',
 '1835745',
 ...]

### Calculate the Correlation Coefficient between the Deaths and Population Columns (of your grouped dataframe)

In [ ]:
#Your code here

### Repeat this process across multiple features
Iterate over the following columns: ['Race', 'Gender', 'Ten-Year Age Groups']. Within your for loop, create a temporary groupby aggregate as we did for the State column above. Then, print any aggregate grouping where the correlation coefficient is less then .95.

In [ ]:
#Your code here

### Combining Features

We can further expand upon our exploration above by testing multiple features against each other!
Complete the code below to print any combination of features where the correlation between population and death is below .95 (or some other appropriate threshold).

In [ ]:
#This could also be accomplished with the combinations() method from the itertools package.
for n, feat1 in enumerate(features):
    for feat2 in features[n:]:
        #Your code here
        #groupby feat1 and feat2!!
        #repeat your code above to check if the correlation is below a [high] threshold.