In [2]:
import pandas as pd

/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [3]:
df = pd.read_csv('causes_of_death.tsv', delimiter='\t')
print(len(df))
df.head()

4115

,Notes,State,State Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Race,Race Code,Deaths,Population,Crude Rate
0,NaN,Alabama,1,< 1 year,1,Female,F,American Indian or Alaska Native,1002-5,14,3579,Unreliable
1,NaN,Alabama,1,< 1 year,1,Female,F,Asian or Pacific Islander,A-PI,24,7443,322.5
2,NaN,Alabama,1,< 1 year,1,Female,F,Black or African American,2054-5,2093,169339,1236.0
3,NaN,Alabama,1,< 1 year,1,Female,F,White,2106-3,2144,347921,616.2
4,NaN,Alabama,1,< 1 year,1,Male,M,Asian or Pacific Islander,A-PI,33,7366,448.0

# Practice Explorations

### Groupby State and Sum the numeric features.

In [34]:
# Groupby State
grouped = df[['State','Population']].groupby('State').sum()
grouped

                                                             Population
State
Alabama               3579744316933934792173661732413640293042167042...
Alaska                2168760316134578132288864936865613228005022606...
Arizona               6214625807482726333596286227000515186605472356...
Arkansas              6218691402549403860663871191269654279764101819...
California            8688455165435191434883069000558543136775836416...
Colorado              1248720956363825097581283421150392035371948923...
Connecticut           1853454220271747190985703728591178222218325115...
Delaware              4259273336480642672793967851107606257732109616...
District of Columbia  3975226508401672827915262178730157749823283846...
Florida               1355856480450751134234214482584774654821406613...
Georgia               7131417634078167116387835442784194477484001718...
Hawaii                1003716895476741065497462490423882421715734127...
Idaho                 5269329532401857925265326232511939147368617734...
Illinois              9124748562670151121984937478670275867117334530...
Indiana               1481010017062799715162104117659832402339252864...
Iowa                  8105210973092288198224133226973348983481123821...
Kansas                6030103913384629631660941088435699309974130168...
Kentucky              7742530494219467999562184438772132101676720321...
Louisiana             5014965721914132148652541005522680633639988367...
Maine                 1931399110973917784258117264456751483086340741...
Maryland              4574394482261063715094467416502345733904301628...
Massachusetts         4549879816529380477628331555344818367230095521...
Michigan              1086535182206880813267112963735121582885413845...
Minnesota             1556336083615974927621619737664647035153045688...
Mississippi           2975329616020519279430173577166532202888108326...
Missouri              1454710718053689852181551811202656437559982425...
Montana               1356715518736613551179991914518473513435370037...
Nebraska              5586551717696194769632158081849520548870026776...
Nevada                7760228953590224136380262407937451252967874051...
New Hampshire         4424341011246046533597117538472859496310139107...
New Jersey            9163817517667509395821182281708316375714696108...
New Mexico            3646042559192194977364234258101672028071382753...
New York              2306416882646773514563392332017983248590915272...
North Carolina        2083230631270069733686211763224728041077173785...
North Dakota          7836245565664876528506951431446258564323932702...
Ohio                  2797722578510007045125293202324951050550115072...
Oklahoma              6152998995303632575063506103795463534348524192...
Oregon                1160720342151873547571175721358162473731244447...
Pennsylvania          4687721249099264347964219990103966518695983070...
Rhode Island          4450128928361844511326487934343231361883125672...
South Carolina        9051176091321064406388471800303351776969441267...
South Dakota          1701231397812417309325883013633013126756517032...
Tennessee             1364815516652283914709160563547746575806176372...
Texas                 3218512995843560627154363325213794545090828342...
Utah                  8687145078561401985842015253927042472455052156...
Vermont               5121255207215509228680634852671989140997460367...
Virginia              4785586462092966097344839613772168236389602314...
Washington            2560167675531126009702716869849553016306169313...
West Virginia         9823170851103581780033785967824939927709012885...
Wisconsin             1230022229679805032701196722488698105292694411...
Wyoming               3260577913366157260874230993242665256805895692...

### Calculate the Correlation Coefficient between the Deaths and Population Columns (of your grouped dataframe)

In [ ]:
#Your code here

### Repeat this process across multiple features
Iterate over the following columns: ['Race', 'Gender', 'Ten-Year Age Groups']. Within your for loop, create a temporary groupby aggregate as we did for the State column above. Then, print any aggregate grouping where the correlation coefficient is less then .95.

In [ ]:
#Your code here

### Combining Features

We can further expand upon our exploration above by testing multiple features against each other!
Complete the code below to print any combination of features where the correlation between population and death is below .95 (or some other appropriate threshold).

In [ ]:
#This could also be accomplished with the combinations() method from the itertools package.
for n, feat1 in enumerate(features):
    for feat2 in features[n:]:
        #Your code here
        #groupby feat1 and feat2!!
        #repeat your code above to check if the correlation is below a [high] threshold.